---

env: local
time_zone: America/New_York
log_records: 1000
firebase_key:
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 5500
  tls_enabled: false
  cert_file: c:/cert/cert.pem
  key_file: c:/cert/key.pem
central_system:
  enabled: false
  url: https://example.com/api
  token: 1234567890
mongo:
  enabled: false
  host: 127.0.0.1
  port: 27017
  user: admin
  password: pass
  database: evsys
redsys:
  enabled: false
  merchant_code: ""
  terminal: "001"
  secret_key: ""
  rest_api_url: "https://sis-t.redsys.es:25443/sis/rest/trataPeticionREST"
  currency: "978"